Tela principal
alexleandr/invicto-app pull request #4
Opened 2023-03-16 01:55 UTC by alexleandr

Nessa etapa foi criada a base para a tela principal da aplicação.

2023-03-16 01:58 UTC, alexleandr commented on src/App.jsx
>  export function App() {
Passei a página Main para a rota padrão '/' e criei uma nova rota '/auth' para a página Auth.

2023-03-16 01:59 UTC, alexleandr commented on src/App.jsx
Passei a página Main para a rota '/' e criei uma rota '/auth' para a página Auth.

2023-03-16 02:52 UTC, CaioVinicius7 requested changes
Ta muito bom, curti o design, são mais detalhes dessa vez, depois é só fazer a parte da responsividade e fazer umas coisinhas bacanas, como o ícone dinâmico e tals

2023-03-16 02:52 UTC, CaioVinicius7 commented on src/components/ViceCard/index.jsx
> +                <BiDrink size='24'/>
Acho que rola deixar esses icones dinâmicos em

2023-03-16 02:52 UTC, CaioVinicius7 commented on src/components/ViceCard/styles.jsx
> +    border: 0 solid #1c1c1c;
coloca assim: 

`border: 1px solid transparent` ou `border: 1px solid  #1c1c1c`

Assim evita o layout shift ao passar aplicar o efeito de hover

2023-03-16 02:52 UTC, CaioVinicius7 commented on src/components/ViceCard/index.jsx
> +                <InfoCircle size='22'/>
Não sei qual sua ideia original, mas acho que aqui poderia abrir um popover com o resumo, se não souber oq é popover da uma olhada no radix. 

Mas também seria interessante abrir um modal/trocar de página ao clicar no card. porém ai talvez não faria sentido esse botão mais o popover, somente caso o pop over seja um resumo mais seco e quando clicasse o modal/página tivesse as informações bem completas.

Digo esse pois talvez fique mais intuitivo e seja uma melhor experiência para o usuário clicar no card todo, já que ele até tem um efeito de hover que parece indicar que o clica faz uma ação.

2023-03-16 02:52 UTC, CaioVinicius7 commented on src/components/ViceCard/styles.jsx
> +    margin-left: 28px;
Talvez seja melhor usar padding ao invés de margin, nesse e nos outro lugares abaixo.

Outra alternativa é reestrutura o html colocando uma div/box em voltar de tudo que seja o corpo ai definindo um padding/margin só, um o `CardBody` ou `BodyContainer`, saca?

2023-03-16 02:52 UTC, CaioVinicius7 commented on src/components/ViceCard/styles.jsx
> +export const TitleContainer = styled.div`
Aqui acho que cairia melhor o nome `CardHeader` ou `HeaderContainer`  e tbm usaria um `styled.header`.

2023-03-16 02:52 UTC, CaioVinicius7 commented on src/components/ViceCard/styles.jsx
> +export const ToolsContainer = styled.div`
Isso aqui tbm poderia ser um `CardFooter` ou `FooterContainer` e um `styled.footer`.

2023-03-16 02:52 UTC, CaioVinicius7 commented on src/components/ViceCard/styles.jsx
Sobre as sugestões de nome, você pode utilizar ou algum dos dois ou `ViceCardHeader`, `ViceCardBody` e `ViceCardFooter `, acho que esses três ficam bem descritivos e não vão "conflitar" com nenhum outro componente, pois está com o nome bem explicito, tanto da parte do card quanto de qual card/componente é esse componente estilizado.

2023-03-16 02:52 UTC, CaioVinicius7 commented on src/pages/Main/index.jsx
> +                <nav>
Uma coisa que até mesmo eu não costumo fazer, mas estou tentando pegar o hábito agora é utilizar listas nesses casos, vi que é bom para o navegador entender melhor o código, isso ajuda muito na acessiblidade.

Caso queira aplicar ficaria algo como:

```html
<nav>
  <ul>
    <li> 
      <a href="#"> ... </a>
    </li>
    <li> 
      <a href="#"> ... </a>
    </li>
  </ul>
</nav>
```

2023-03-16 02:52 UTC, CaioVinicius7 commented on src/pages/Main/index.jsx
Da pra componentizar essas partes da página, você pode criar um diretório `components` dentro do diretório dessa página e dentro dele criar um diretório para cada componentem ai fica aquele esquesma.


/ Página
  / Main
    / Components
       / Header
          index.jsx
          styles.js

2023-03-16 02:52 UTC, CaioVinicius7 commented on src/pages/Main/styles.jsx
Não se esqueça da responsividade

2023-03-16 02:55 UTC, CaioVinicius7 commented
Cara, uma boa para os icones dinâmicos é isso aqui: https://www.radix-ui.com/docs/primitives/utilities/slot

Depois da uma olhada por cima, ai eu te ajudo a implementar no código.

2023-03-17 18:19 UTC, CaioVinicius7 requested changes

2023-03-17 18:19 UTC, CaioVinicius7 commented on src/components/Header/index.jsx
> +            <img src={logo} />
Coloca um `alt=""`

Pode passar vazio mesmo ou pode colocar tipo alt="Logo Invicto"

2023-03-17 18:19 UTC, CaioVinicius7 commented on src/pages/Main/index.jsx
> +                <aside>
Tbm da pra componentizar esse `aside`

2023-03-17 18:59 UTC, CaioVinicius7 approved these changes

2023-03-17 18:59 UTC, CaioVinicius7 approved these changes

2023-03-17 18:59 UTC, merged