Ferramentas da tela principal
alexleandr/invicto-app pull request #5
Opened 2023-03-23 02:37 UTC by alexleandr

Nessa etapa foram feitas alterações referentes as funcionalidades dos ícones dos ViceCards e do botão de Adicionar Ícone. A responsividade da página e alterações na tela de login/cadastro também foram adicionadas.

2023-03-23 23:30 UTC, CaioVinicius7 requested changes

2023-03-23 23:30 UTC, CaioVinicius7 commented on src/pages/Main/components/MainPageAside/CreateVice/styles.jsx
> +    ${buttonStyles}
Só confirmando, da pra fazer isso mesmo hehe

![image](https://user-images.githubusercontent.com/62827681/227385384-55703554-83ae-4dfe-abe2-2bc17a61a4f6.png)

2023-03-23 23:30 UTC, CaioVinicius7 commented on src/pages/Main/components/ViceCard/components/DeleteVice/styles.jsx
> +export const DeleteViceCancel = styled(AlertDialog.Cancel)`
O css não está aqui, mas vi o preview de como está, e acho que seria legal aumentar o tamanho do modal, acho que os botões estão muito grudados.

2023-03-24 00:13 UTC, CaioVinicius7 commented
Da uma verificada no que ta acontecendo aqui patrão

![image](https://user-images.githubusercontent.com/62827681/227391670-17d444b7-b7bc-47ce-9bab-bbc58d04aff2.png)

2023-03-24 22:28 UTC, alexleandr commented on src/pages/Main/styles.jsx
> +        grid-template-rows: repeat(auto-fill, 200px);
As últimas linhas do grid ficavam maiores que as anteriores pra ocupar todo o espaço disponível no grid container. Esse repeat(auto-fill, 200px) foi a solução que encontrei pra elas ficarem todas do mesmo tamanho. O auto-fill cria espaços brancos não alocados que estão "esperando" mais linhas. Já o auto-fit, 'irmão' do auto-fill, aumenta a altura das linhas pra preencher todo o espaço disponível no grid container.

2023-03-28 16:25 UTC, CaioVinicius7 approved these changes

2023-03-28 16:26 UTC, merged